import type { Place, Event, Category } from '@/types'

export const MOCK_CATEGORIES: Category[] = [
  { id: '2', slug: 'cafes', name: 'Cafés', description: 'Coffee, tea, and cozy corners', icon: 'Coffee', color: '#D98A6C', sort_order: 1 },
  { id: '3', slug: 'bars', name: 'Bars & Cafés', description: 'Borrel, cocktails, and late nights', icon: 'Wine', color: '#A78BFA', sort_order: 2 },
  { id: '4', slug: 'shopping', name: 'Shopping', description: 'Boutiques, markets, and stores', icon: 'ShoppingBag', color: '#60A5FA', sort_order: 3 },
  { id: '5', slug: 'attractions', name: 'Attractions', description: 'Museums, monuments, and landmarks', icon: 'Landmark', color: '#F59E0B', sort_order: 4 },
  { id: '6', slug: 'parks', name: 'Parks & Nature', description: 'Green spaces and outdoor escapes', icon: 'Trees', color: '#4ADE80', sort_order: 5 },
  { id: '7', slug: 'hidden-gems', name: 'Hidden Gems', description: 'Off the beaten path', icon: 'MapPin', color: '#FB7185', sort_order: 6 },
]

export const MOCK_PLACES: Place[] = [
  {
    id: 'p3',
    name: 'Herberg \'t Plein',
    slug: 'herberg-t-plein',
    category_id: '3',
    description: 'A beloved brown café on the Marktplein with a lively atmosphere. Great for a cold beer, a nice wine, or an amazing hot chocolate. The kitchen serves hearty Dutch classics. A Meppel institution since decades.',
    short_description: 'Iconic brown café on the square',
    price_level: 1,
    latitude: 52.6962,
    longitude: 6.1958,
    address: 'Marktplein 1',
    postcode: '7941 AA',
    city: 'Meppel',
    phone: '+31 522 243 456',
    website: 'https://herbergthetplein.nl',
    instagram: '@herbergthetplein',
    hours: {
      monday: '10:00-01:00',
      tuesday: '10:00-01:00',
      wednesday: '10:00-01:00',
      thursday: '10:00-01:00',
      friday: '10:00-02:00',
      saturday: '10:00-02:00',
      sunday: '12:00-01:00',
    },
    photos: ['https://images.unsplash.com/photo-1470337458703-46ce17556838?w=800', 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800', 'https://images.unsplash.com/photo-1529504426707-d1d7a0dc458a?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.2,
    review_count: 1626,
    trending_score: 91.0,
    is_featured: true,
    tags: ['lively', 'historic', 'beer'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '3', slug: 'bars', name: 'Bars & Cafés', description: 'Borrel, cocktails, and late nights', icon: 'Wine', color: '#A78BFA', sort_order: 3 },
  },
  {
    id: 'p5',
    name: 'Grand Café De Wheem',
    slug: 'grand-cafe-de-wheem',
    category_id: '2',
    description: 'A popular grand café with a spacious terrace overlooking the canal. Great for coffee, lunch, or an evening drink. The homemade apple pie is legendary in Meppel. A favourite spot for locals and visitors alike.',
    short_description: 'Canalside grand café',
    price_level: 2,
    latitude: 52.6963,
    longitude: 6.1948,
    address: 'Prinsengracht 28',
    postcode: '7941 AA',
    city: 'Meppel',
    phone: '+31 522 240 055',
    website: 'https://grandcafedewheem.nl',
    instagram: '@grandcafedewheem',
    hours: {
      monday: '09:00-18:00',
      tuesday: '09:00-18:00',
      wednesday: '09:00-18:00',
      thursday: '09:00-21:00',
      friday: '09:00-22:00',
      saturday: '09:00-22:00',
      sunday: '10:00-18:00',
    },
    photos: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.5,
    review_count: 681,
    trending_score: 89.0,
    is_featured: true,
    tags: ['canal-view', 'terrace', 'lunch'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '2', slug: 'cafes', name: 'Cafés', description: 'Coffee, tea, and cozy corners', icon: 'Coffee', color: '#D98A6C', sort_order: 2 },
  },
  {
    id: 'p8',
    name: 'Drukkerijmuseum',
    slug: 'drukkerijmuseum',
    category_id: '5',
    description: 'The Meppel Printing Museum is a fascinating look at the city\'s rich printing heritage. Passionate volunteers demonstrate historic printing techniques and graphic arts. A must-visit for history buffs and families — children especially love the interactive demonstrations.',
    short_description: 'Historic printing museum',
    price_level: 1,
    latitude: 52.6975,
    longitude: 6.1975,
    address: 'Kerkstraat 30',
    postcode: '7941 AA',
    city: 'Meppel',
    phone: '+31 522 244 567',
    website: 'https://drukkerijmuseum.nl',
    instagram: null,
    hours: {
      wednesday: '10:00-16:00',
      thursday: '10:00-16:00',
      friday: '10:00-16:00',
      saturday: '10:00-16:00',
    },
    photos: ['https://images.unsplash.com/photo-1566753323358-c157698e2046?w=800', 'https://images.unsplash.com/photo-1582560475093-b56584a44ffd?w=800', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.4,
    review_count: 25,
    trending_score: 82.0,
    is_featured: true,
    tags: ['museum', 'history', 'family-friendly'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '5', slug: 'attractions', name: 'Attractions', description: 'Museums, monuments, and landmarks', icon: 'Landmark', color: '#F59E0B', sort_order: 5 },
  },
  {
    id: 'p9',
    name: 'Meppeler Toren',
    slug: 'meppeler-toren',
    category_id: '5',
    description: 'The 45-metre-high tower of the Grote of Mariakerk is the proud centre of Meppel. Built after Meppel became ecclesiastically independent in 1422, the tower once attracted traders and craftsmen from far and wide. Climb the 147 steps for a fantastic view over the city and surrounding Drenthe countryside. Every Thursday the weekly market is held at its base.',
    short_description: 'Iconic 15th-century church tower',
    price_level: 1,
    latitude: 52.6968,
    longitude: 6.1962,
    address: 'Grote Kerkstraat',
    postcode: '7941 AA',
    city: 'Meppel',
    phone: null,
    website: 'https://meppeltoren.nl',
    instagram: null,
    hours: {
      thursday: '10:00-16:00',
      saturday: '10:00-16:00',
    },
    photos: ['https://images.unsplash.com/photo-1543632579090-ffcee0f5c41d?w=800', 'https://images.unsplash.com/photo-1596394723269-e8e81743c438?w=800', 'https://images.unsplash.com/photo-1519999489361-1abcb1007447?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.0,
    review_count: 45,
    trending_score: 85.0,
    is_featured: true,
    tags: ['historic', 'viewpoint', 'landmark'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '5', slug: 'attractions', name: 'Attractions', description: 'Museums, monuments, and landmarks', icon: 'Landmark', color: '#F59E0B', sort_order: 5 },
  },
  {
    id: 'p10',
    name: 'Molen de Vlijt',
    slug: 'molen-de-vlijt',
    category_id: '5',
    description: 'A beautifully restored mill situated on the canal in the centre of Meppel. One of the last remaining mills from the city\'s original 20. The mill is well-maintained and can still turn — a picturesque sight along the water. Meppel once had corn mills, sawmills, oil mills, and bark mills for the leather tanning industry.',
    short_description: 'Restored canal-side mill',
    price_level: 0,
    latitude: 52.6958,
    longitude: 6.1945,
    address: 'Vlijt',
    postcode: '7941 AA',
    city: 'Meppel',
    phone: null,
    website: 'https://molendevlijt.nl',
    instagram: null,
    hours: null,
    photos: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800', 'https://images.unsplash.com/photo-1473496169904-658ba7c44d3a?w=800', 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.2,
    review_count: 18,
    trending_score: 80.0,
    is_featured: false,
    tags: ['historic', 'photo-spot', 'canal'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '5', slug: 'attractions', name: 'Attractions', description: 'Museums, monuments, and landmarks', icon: 'Landmark', color: '#F59E0B', sort_order: 5 },
  },
  {
    id: 'p11',
    name: 'Stadspark Meppel',
    slug: 'stadspark-meppel',
    category_id: '6',
    description: 'Meppel\'s central park with winding paths, centuries-old trees, and a picturesque pond. The perfect spot for a quiet walk, a picnic, or just sitting on a bench and enjoying the greenery. A local favourite for morning runs and afternoon strolls.',
    short_description: 'Meppel\'s central green oasis',
    price_level: 0,
    latitude: 52.6980,
    longitude: 6.1920,
    address: 'Stadspark',
    postcode: '7941 AA',
    city: 'Meppel',
    phone: null,
    website: 'https://stadsparkmeppel.nl',
    instagram: null,
    hours: null,
    photos: ['https://images.unsplash.com/photo-1448375240586-882707db888b?w=800', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800', 'https://images.unsplash.com/photo-1473496169904-658ba7c44d3a?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.7,
    review_count: 52,
    trending_score: 87.0,
    is_featured: true,
    tags: ['nature', 'walking', 'family-friendly'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '6', slug: 'parks', name: 'Parks & Nature', description: 'Green spaces and outdoor escapes', icon: 'Trees', color: '#4ADE80', sort_order: 6 },
  },
  {
    id: 'p12',
    name: 'O\'moda',
    slug: 'omoda-meppel',
    category_id: '4',
    description: 'The go-to shoe and fashion store on Meppel\'s Hoofdstraat. A wide selection of trendy footwear, bags, and clothing for the whole family. Known for excellent service and the latest styles.',
    short_description: 'Fashion and footwear',
    price_level: 2,
    latitude: 52.6966,
    longitude: 6.1956,
    address: 'Hoofdstraat 40',
    postcode: '7941 AB',
    city: 'Meppel',
    phone: '+31 522 244 300',
    website: 'https://www.omoda.nl',
    instagram: '@omoda_shoes',
    hours: {
      monday: '10:00-18:00',
      tuesday: '09:00-18:00',
      wednesday: '09:00-18:00',
      thursday: '09:00-21:00',
      friday: '09:00-18:00',
      saturday: '09:00-17:00',
    },
    photos: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800', 'https://images.unsplash.com/photo-1567401893414-76b7b7661be0?w=800', 'https://images.unsplash.com/photo-1555529669-e69e7aa0792e?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.3,
    review_count: 87,
    trending_score: 78.0,
    is_featured: false,
    tags: ['shopping', 'fashion', 'shoes'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '4', slug: 'shopping', name: 'Shopping', description: 'Boutiques, markets, and stores', icon: 'ShoppingBag', color: '#60A5FA', sort_order: 4 },
  },
  {
    id: 'p13',
    name: 'Grandcafé Salud',
    slug: 'grandcafe-salud',
    category_id: '3',
    description: 'A vibrant grand café in the centre of Meppel where enjoying yourself is the main focus. Great for coffee, lunch, borrel, and dinner. Their sunny terrace is the perfect spot on warm days. A lively atmosphere with a friendly team.',
    short_description: 'Coffee, lunch, borrel & dinner',
    price_level: 2,
    latitude: 52.6964,
    longitude: 6.1954,
    address: 'Hoofdstraat 35',
    postcode: '7941 AB',
    city: 'Meppel',
    phone: '+31 522 745 090',
    website: 'https://grandcafesalud.nl',
    instagram: '@grandcafesalud',
    hours: {
      tuesday: '10:00-22:00',
      wednesday: '10:00-22:00',
      thursday: '10:00-22:00',
      friday: '10:00-01:00',
      saturday: '10:00-01:00',
      sunday: '10:00-22:00',
    },
    photos: ['https://images.unsplash.com/photo-1514933651103-96f7574e2432?w=800', 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800', 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.3,
    review_count: 120,
    trending_score: 86.0,
    is_featured: false,
    tags: ['terrace', 'lively', 'borrel'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '3', slug: 'bars', name: 'Bars & Cafés', description: 'Borrel, cocktails, and late nights', icon: 'Wine', color: '#A78BFA', sort_order: 3 },
  },
  {
    id: 'p15',
    name: 'Proeverij Taste & Toast',
    slug: 'proeverij-taste-and-toast',
    category_id: '2',
    description: 'A cosy tasting café specialising in creative toasts, fresh juices, and specialty coffee. Perfect for a light lunch or a quick bite. The avocado toast and homemade smoothie bowls are standouts.',
    short_description: 'Creative toasts and fresh juices',
    price_level: 1,
    latitude: 52.6967,
    longitude: 6.1958,
    address: 'Hoofdstraat 28',
    postcode: '7941 AB',
    city: 'Meppel',
    phone: '+31 522 745 100',
    website: 'https://tasteandtoast.nl',
    instagram: '@tasteandtoast',
    hours: {
      tuesday: '09:00-17:00',
      wednesday: '09:00-17:00',
      thursday: '09:00-17:00',
      friday: '09:00-17:00',
      saturday: '09:00-17:00',
      sunday: '10:00-16:00',
    },
    photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800'],
    photo_blurhashes: [],
    avg_rating: 4.5,
    review_count: 78,
    trending_score: 83.0,
    is_featured: false,
    tags: ['lunch', 'healthy', 'coffee'],
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
    category: { id: '2', slug: 'cafes', name: 'Cafés', description: 'Coffee, tea, and cozy corners', icon: 'Coffee', color: '#D98A6C', sort_order: 2 },
  },
]

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    name: 'Meppelse Markt',
    slug: 'meppelse-markt',
    description: 'The weekly market on Thursday at the Marktplein. Fresh produce, flowers, cheese, bread, and local specialties from Drenthe farmers. A Meppel tradition for centuries — the perfect way to start your Thursday.',
    category: 'markets',
    venue_name: 'Marktplein',
    venue_address: 'Marktplein, Meppel',
    latitude: 52.6962,
    longitude: 6.1958,
    start_datetime: new Date(Date.now() + 2 * 86400000).toISOString(),
    end_datetime: new Date(Date.now() + 2 * 86400000 + 5 * 3600000).toISOString(),
    price: null,
    price_currency: 'EUR',
    photo: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80',
    photo_blurhash: null,
    organizer_name: 'Gemeente Meppel',
    organizer_url: null,
    attendee_count: 500,
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
  },
  {
    id: 'e2',
    name: 'Koopzondag Meppel',
    slug: 'koopzondag-meppel',
    description: 'Monthly shopping Sunday in the centre of Meppel. All shops on the Hoofdstraat and surrounding streets are open from 12:00 to 17:00. Special promotions, live music, and a festive atmosphere throughout the city centre.',
    category: 'shopping',
    venue_name: 'Centrum Meppel',
    venue_address: 'Hoofdstraat, Meppel',
    latitude: 52.6966,
    longitude: 6.1956,
    start_datetime: new Date(Date.now() + 14 * 86400000).toISOString(),
    end_datetime: new Date(Date.now() + 14 * 86400000 + 5 * 3600000).toISOString(),
    price: null,
    price_currency: 'EUR',
    photo: 'https://images.unsplash.com/photo-1555529669-e69e7aa0792e?w=800&q=80',
    photo_blurhash: null,
    organizer_name: 'Winkeliersvereniging Meppel',
    organizer_url: null,
    attendee_count: 800,
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
  },
  {
    id: 'e4',
    name: 'Expositie: Drentse Landschappen',
    slug: 'expositie-drentse-landschappen',
    description: 'An exhibition of landscape paintings by local Drenthe artists. Featuring works by Jansen, De Vries, and Van der Meer. A beautiful tribute to the rolling heathlands, ancient forests, and charming villages of Drenthe.',
    category: 'art',
    venue_name: 'Drukkerijmuseum',
    venue_address: 'Kerkstraat 30, Meppel',
    latitude: 52.6975,
    longitude: 6.1975,
    start_datetime: new Date(Date.now() + 5 * 86400000).toISOString(),
    end_datetime: new Date(Date.now() + 30 * 86400000).toISOString(),
    price: 5,
    price_currency: 'EUR',
    photo: 'https://images.unsplash.com/photo-1531913764164-f85c3e03b1ec?w=800&q=80',
    photo_blurhash: null,
    organizer_name: 'Drukkerijmuseum',
    organizer_url: null,
    attendee_count: 45,
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
  },
  {
    id: 'e5',
    name: 'Yoga in het Stadspark',
    slug: 'yoga-in-het-stadspark',
    description: 'Outdoor yoga session in the beautiful Stadspark Meppel. All levels welcome. Bring your own mat and water. Followed by herbal tea and a healthy snack. A perfect way to start your Sunday morning.',
    category: 'sports',
    venue_name: 'Stadspark Meppel',
    venue_address: 'Stadspark, Meppel',
    latitude: 52.6980,
    longitude: 6.1920,
    start_datetime: new Date(Date.now() + 7 * 86400000).toISOString(),
    end_datetime: new Date(Date.now() + 7 * 86400000 + 3600000).toISOString(),
    price: 10,
    price_currency: 'EUR',
    photo: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    photo_blurhash: null,
    organizer_name: 'Meppel Wellness',
    organizer_url: null,
    attendee_count: 28,
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
  },
  {
    id: 'e6',
    name: 'Live Muziek bij Herberg \'t Plein',
    slug: 'live-muziek-herberg-t-plein',
    description: 'Every Friday night, Herberg \'t Plein hosts live music from local Drenthe bands. From blues to rock, there\'s always something great on stage. Free entry, great atmosphere, and cold beers.',
    category: 'music',
    venue_name: 'Herberg \'t Plein',
    venue_address: 'Marktplein 1, Meppel',
    latitude: 52.6962,
    longitude: 6.1958,
    start_datetime: new Date(Date.now() + 5 * 86400000 + 19 * 3600000).toISOString(),
    end_datetime: new Date(Date.now() + 6 * 86400000 + 1 * 3600000).toISOString(),
    price: null,
    price_currency: 'EUR',
    photo: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    photo_blurhash: null,
    organizer_name: 'Herberg \'t Plein',
    organizer_url: null,
    attendee_count: 150,
    created_by: null,
    created_at: '2026-01-01',
    updated_at: '2026-05-01',
  },
]

export function isSupabaseAvailable(): boolean {
  return !!(
    process.env.NEXT_PUBLIC_SUPABASE_URL &&
    !process.env.NEXT_PUBLIC_SUPABASE_URL.includes('placeholder')
  )
}

export const MOCK_REVIEWS = [
  {
    id: 'r5',
    place_id: 'p3',
    user_id: 'u5',
    rating: 5,
    text: 'Perfect spot for a rainy afternoon. Great coffee, cozy atmosphere, and the homemade apple pie is to die for!',
    photos: [],
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    user: {
      id: 'u5',
      username: 'CoffeeAddict',
      avatar_url: null,
    },
  },
]
